apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-securitypartyroleapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-securitypartyroleapi
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Values.component.name}}
        impl: {{.Release.Name}}-securitypartyroleapi
        version: {{.Values.securitypartyrole.versionlabel}}
    spec:
      containers:
      - name: {{.Release.Name}}-securitypartyrole
        image: {{.Values.securitypartyrole.image}}
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}
        - name: MONGODB_HOST
          value: {{.Release.Name}}-mongodb
        - name: MONGODB_PORT
          value: "{{.Values.mongodb.port}}"
        - name: MONGODB_DATABASE
          value: {{.Values.mongodb.database}}
        - name: NODE_ENV
          value: production
        imagePullPolicy: Always
        ports:
        - name: {{.Release.Name}}-sprapi # sprapi => acronym for (S)ecurity(P)arty(R)ole(A)pi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/partyRole
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30