apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-partyapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-partyapi
  template:
    metadata:
      labels:
        impl: {{.Release.Name}}-partyapi
        app: {{.Release.Name}}-{{.Values.component.name}}
        version:  partyapi-0.1
    spec:
      containers:
      - name: {{.Release.Name}}-partyapi         
        image: {{.Values.api.image}}
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}           
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}
        - name: MONGODB_HOST
          value: {{.Release.Name}}-mongodb
        - name: MONGODB_PORT
          value: "{{.Values.mongodb.port}}"
        - name: MONGODB_DATABASE
          value: {{.Values.mongodb.database}}
        - name: NODE_ENV
          value: production
        imagePullPolicy: Always  
        ports:
        - name: {{.Release.Name}}-papi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
      imagePullSecrets:
        - name: sergejp-tmf-pull-robot-pull-secret