apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-resourceinventoryapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-resourceinventoryapi
  template:
    metadata:
      labels:
        impl: {{.Release.Name}}-resourceinventoryapi
        app: {{.Release.Name}}-{{.Values.component.name}}
        version:  resourceinventoryapi-0.3
    spec:
      containers:
      - name: {{.Release.Name}}-resourceinventoryapi         
        image: akumartmf/resourceinventoryapi:0.1
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}           
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}
        - name: MONGODB_HOST
          value: {{.Release.Name}}-mongodb
        - name: MONGODB_PORT
          value: "{{.Values.mongodb.port}}"
        - name: MONGODB_DATABASE
          value: {{.Values.mongodb.database}}
        - name: NODE_ENV
          value: production
        imagePullPolicy: Always  
        ports:
        - name: {{.Release.Name}}-rscinvapi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/resourceInventoryManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30