apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-corepartyroleapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-corepartyroleapi
  template:
    metadata:
      labels:
        impl: {{.Release.Name}}-corepartyroleapi
        app: {{.Release.Name}}-{{.Values.component.name}}
        version:  {{.Values.api.corepartyrole.versionlabel}}
    spec:
      containers:
      - name: {{.Release.Name}}-corepartyroleapi
        image: {{.Values.api.corepartyrole.image}}
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}           
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}
        - name: MONGODB_HOST
          value: {{.Release.Name}}-mongodb
        - name: MONGODB_PORT
          value: "{{.Values.mongodb.port}}"
        - name: MONGODB_DATABASE
          value: {{.Values.mongodb.database}}-corepartyrole
          # Appended "-corepartyrole" suffix so that corepartyrole and "security function" partyrole apis do not share the same db,
          # otherwise both can see the canvasSystem Admin role, for example.
        - name: NODE_ENV
          value: production
        imagePullPolicy: Always
        ports:
        - name: {{.Release.Name}}-cprapi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/partyRole
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30